{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "trusted": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Bienvenue au DAB\n",
      "Authentification échouée\n"
     ]
    }
   ],
   "source": [
    "class CompteBancaire:\n",
    "    def __init__(self, numero_carte, pin, solde=0):\n",
    "        self.numero_carte = numero_carte\n",
    "        self.pin = pin\n",
    "        self.solde = solde\n",
    "        self.releves = []\n",
    "\n",
    "    def deposer(self, montant):\n",
    "        self.solde += montant\n",
    "        self.releves.append(f\"Dépôt de {montant}€\")\n",
    "        return self.solde\n",
    "\n",
    "    def retirer(self, montant):\n",
    "        if montant > self.solde:\n",
    "            return \"Solde insuffisant\"\n",
    "        self.solde -= montant\n",
    "        self.releves.append(f\"Retrait de {montant}€\")\n",
    "        return self.solde\n",
    "\n",
    "    def consulter_solde(self):\n",
    "        return self.solde\n",
    "\n",
    "    def consulter_releves(self):\n",
    "        return self.releves\n",
    "\n",
    "    def changer_pin(self, ancien_pin, nouveau_pin):\n",
    "        if self.pin == ancien_pin:\n",
    "            self.pin = nouveau_pin\n",
    "            return \"PIN changé avec succès\"\n",
    "        return \"Ancien PIN incorrect\"\n",
    "\n",
    "class DAB:\n",
    "    def __init__(self):\n",
    "        self.comptes = {}\n",
    "\n",
    "    def ajouter_compte(self, numero_carte, pin, solde=0):\n",
    "        self.comptes[numero_carte] = CompteBancaire(numero_carte, pin, solde)\n",
    "\n",
    "    def authentifier(self, numero_carte, pin):\n",
    "        compte = self.comptes.get(numero_carte)\n",
    "        if compte and compte.pin == pin:\n",
    "            return compte\n",
    "        return None\n",
    "\n",
    "def main():\n",
    "    dab = DAB()\n",
    "    dab.ajouter_compte(\"123456789\", \"1234\", 1000)\n",
    "\n",
    "    print(\"Bienvenue au DAB\")\n",
    "    numero_carte = input(\"Entrez votre numéro de carte : \")\n",
    "    pin = input(\"Entrez votre PIN : \")\n",
    "\n",
    "    compte = dab.authentifier(numero_carte, pin)\n",
    "    if compte:\n",
    "        print(\"Authentification réussie\")\n",
    "        while True:\n",
    "            print(\"\\n1. Dépôt\")\n",
    "            print(\"2. Retrait\")\n",
    "            print(\"3. Consulter solde\")\n",
    "            print(\"4. Consulter relevés\")\n",
    "            print(\"5. Changer PIN\")\n",
    "            print(\"6. Quitter\")\n",
    "            choix = input(\"Choisissez une option : \")\n",
    "\n",
    "            if choix == \"1\":\n",
    "                montant = float(input(\"Entrez le montant à déposer : \"))\n",
    "                nouveau_solde = compte.deposer(montant)\n",
    "                print(f\"Nouveau solde : {nouveau_solde}€\")\n",
    "            elif choix == \"2\":\n",
    "                montant = float(input(\"Entrez le montant à retirer : \"))\n",
    "                nouveau_solde = compte.retirer(montant)\n",
    "                if isinstance(nouveau_solde, str):\n",
    "                    print(nouveau_solde)\n",
    "                else:\n",
    "                    print(f\"Nouveau solde : {nouveau_solde}€\")\n",
    "            elif choix == \"3\":\n",
    "                print(f\"Solde actuel : {compte.consulter_solde()}€\")\n",
    "            elif choix == \"4\":\n",
    "                print(\"Relevés :\")\n",
    "                for releve in compte.consulter_releves():\n",
    "                    print(releve)\n",
    "            elif choix == \"5\":\n",
    "                ancien_pin = input(\"Entrez votre ancien PIN : \")\n",
    "                nouveau_pin = input(\"Entrez votre nouveau PIN : \")\n",
    "                print(compte.changer_pin(ancien_pin, nouveau_pin))\n",
    "            elif choix == \"6\":\n",
    "                print(\"Merci d'avoir utilisé le DAB\")\n",
    "                break\n",
    "            else:\n",
    "                print(\"Option invalide\")\n",
    "    else:\n",
    "        print(\"Authentification échouée\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "trusted": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
